Update <Button /> component for Teheran
ridi/rsg pull request #13
Opened 2018-08-30 08:41 UTC by incleaf

This PR depends on #12 and shouldn't be merged before #12 gets merged.

## Primary changes
- Add flexibility with new props: `component`, `href`
- Remove props: `wrapper`, `wrapperProps`
- Pass rest parameters of given props into the Wrapper
- Place its stylesheet in the same directory

2018-08-30 09:59 UTC, antiline commented on stories/rui.tsx
> +      <CheckBox checked={true} disabled={true} onChange={() => null}>리디북스</CheckBox><br />
중복인것 같습니다.

2018-08-30 10:01 UTC, antiline commented on stories/rui.tsx
> +        component={(props) => (
이렇게 컴포넌트를 사용하는 경우에는 color="blue" spinner={true} 같은 기능은 못쓰는거죠?
css class 도 지정해야 하고.

2018-08-30 10:09 UTC, incleaf commented on stories/rui.tsx
> +        component={(props) => (
가능합니다. 다만 콜백으로 넘어오는 props의 className을 그대로 사용해야 해요. 그러고보니 콜백 파라미터의 타입이 틀렸네요 ㅎㅎ; 수정하겠습니다.

2018-08-30 10:13 UTC, antiline requested changes

2018-08-30 10:13 UTC, antiline commented on stories/rui.tsx
> +        component={(props) => (
component 를 사용하게 되는 케이스는 아까 미팅때 말씀하신 router 관련된거랑 또 뭐가 있을까요?

제 생각에는 예상하기 어려운 상태로 돔이 바뀌는거면 컴포넌트를 새로 하나 만들어야 하는거 아닌가 생각되서요.
예상 가능한 케이스라면 옵션으로 처리해야 하는거 아닌지..

2018-08-30 10:31 UTC, krazijames commented on stories/rui.tsx
> +        component={(props) => (
```jsx
<Button component="a" href="/">Anchor</Button>
<Button component={Link} to="/">Router Link</Button>
```
아마 이런 정도의 케이스가 많지 않을까요? 그리고 `className`은 알아서 병합되고 있고, `{...extraProps}`로 props를 넘기고 있어서 component 종류에 따른 처리는 딱히 필요 없다는 생각이듭니다. 어차피 component에 값을 넘기는 것은 사용하는 쪽에서 넘기는 것이니까 적절한 props를 같이 넘기겠지요..

2018-08-30 10:43 UTC, krazijames commented on components/src/button/index.tsx
> +    Wrapper = 'a';
`a` 태그만 따로 처리하는 게 바깥에서 보기엔 다소 암묵적일 수 있을 것 같아요. `extraProps`가 컴포넌트에 바로 전달 된다는 것만 명확히 하고 `component`와 그에 따른 `props`는 사용자에게 맡기는 것이 좋을 것 같습니다.

2018-08-31 02:45 UTC, krazijames commented on components/scripts/build.js
> +    cssBuilder,
`components/dist` 폴더가 없으면 에러가 납니다 😢

2018-08-31 02:47 UTC, krazijames commented on components/scripts/build.js
> +        await bundle.generate(options.output);
이 라인은 중복 빌드라서 제거해도 될 것 같습니다.

2018-08-31 02:58 UTC, incleaf commented on components/src/button/index.tsx
> +    Wrapper = 'a';
```jsx
// 1번
<Button component="a" href="https://ridibooks.com">리디북스</Button>
```

```jsx
// 2번
<Button href="https://ridibooks.com">리디북스</Button>
```

언급해주신 암묵적인 부분이 있다는 것에는 저도 동의하는 부분입니다.  제가 `href` prop을 추가 한 이유는 편리함 때문이었습니다. 버튼을 링크로 사용하는 경우가 잦은데 1번 코드처럼 `component`를 매번 추가해줘야 해서요, 2번의 경우엔 자동완성 측면에서도 유리한 점이 있습니다. 개인적으로는 2번 코드를 봤을 때 링크처럼 작동할 것이라고 다들 예상하지 않을까 싶고, 2로 결정할 경우엔 문서에도 남기는 것이 좋을 것 같습니다.

@antiline 어떻게 생각하시나요?

2018-08-31 02:59 UTC, incleaf commented on components/scripts/build.js
> +        await bundle.generate(options.output);
이건 #12 에서 진행하는 것으로 할게요~

2018-08-31 09:52 UTC, antiline commented on components/src/button/index.tsx
> +    Wrapper = 'a';
논의 결과 1번으로 진행합니다. 
기본적인 개발 정책은 아래와 같이 합니다.

- RSG는 스타일 핸들링만 한다
- 예를들어 페이지네이터와 같은 경우 마크업을 만들기 위해  전달해야 하는 옵션들은 스타일 핸들링에 들어갑니다.

2018-08-31 09:53 UTC, antiline commented on stories/rui.tsx
> +        component={(props) => (
여기의 부적절한 예제는 적절한 예제로 수정합니다.

2018-08-31 10:16 UTC, antiline approved these changes

2018-08-31 10:36 UTC, incleaf commented on components/scripts/build.js
> +    cssBuilder,
@krazijames 수정했습니다 👍

2018-09-03 01:24 UTC, krazijames approved these changes

2018-09-03 02:04 UTC, merged