Feature/pagination
ridi/rsg pull request #23
Opened 2018-09-12 07:03 UTC by JunuSinclair

2018-09-12 10:38 UTC, kyungmi requested changes

2018-09-12 10:38 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
1. `Checkbox`컴포넌트에서는 `component`라는 이름이 쓰이고 있는데요. 통일하는게 좋을 것 같습니다.
2. `getProps(page)`를 사용해서 각 페이지 버튼 별로 다른 속성(props)이 들어갈 수 있도록 구현되어 있는 것 같은데요. 어떤 유즈케이스가 있을까요? 이벤트 리스너가 아닌 함수를 프로퍼티로 전달하는 것이 일반적이진 않아보여서요.

2018-09-12 10:38 UTC, kyungmi commented on components/src/pagination/index.tsx
> +  });
`component`는 `buttonDefaultStyle`이라는 함수 명에는 맞지 않는 것 같아요.
`getProps()`와 맞춰서 `getDefaultProps()` 정도가 어떨까 싶네요.

2018-09-12 10:38 UTC, kyungmi commented on components/src/pagination/index.tsx
> +                active: currentPage === pageNumber,
`active` 클래스가 `<Button>`의 css 파일에 정의되어 있지 않은데, 삭제해도 될 것 같아요.
만약에 페이지가 선택되었을 때 `color="blue"` 외에도 `.active` 클래스를 꼭 넣어줘야 한다면, 직접 클래스를 넣는게 아니라 `disabled`, `color`, `outline` 처럼 `<Button>` 의 프로퍼티로 작업되는게 좋을 것 같고요.

2018-09-12 10:38 UTC, kyungmi commented on components/src/pagination/index.tsx
> +                'FirstPageButton',
`FirstPageButton`, `PrevPageButton`, `NextPageButton`등은 사용되는 곳이 없는 것 같은데 삭제해도 될 것 같습니다.

2018-09-12 10:38 UTC, kyungmi commented on components/src/pagination/index.tsx
> +                museo_sans: true,
`museo_sans` 클래스는 어디에 정의되어 있나요?

2018-09-12 10:38 UTC, kyungmi commented on components/src/pagination/index.tsx
> +          </Button>
`<Button>` 인스턴스 생성의 중복된 부분을 메서드로 분리하면 어떨까요?

2018-09-12 23:45 UTC, incleaf requested changes

2018-09-12 23:45 UTC, incleaf commented on components/src/pagination/index.tsx
> +    buttonComponent?: 'button' | 'a' | Link;
1. 경미님 [코멘트](https://github.com/ridi/rsg/pull/23/files#r216969320)처럼 `component`로 통일이 필요할 것 같습니다.
2. 페이지네이션 컴포넌트가 Link에 직접적인 디펜던시를 가지고 있으면 안됩니다. Button 컴포넌트 참고 부탁드려요~

2018-09-12 23:45 UTC, incleaf commented on components/src/pagination/index.tsx
> +  });
저도 같은 의견입니다. 다만 `getDefaultProps`는 주체가 명확하지 않으니 조금 더 명확하게 `getButtonDefaultProps`는 어떨까요?

2018-09-12 23:46 UTC, incleaf commented
@JunuSinclair Please update the title and description of this PR appropriately :)

2018-09-13 02:03 UTC, JunuSinclair commented on components/src/pagination/index.tsx
> +                museo_sans: true,
museoSans 로 클래스명이 수정되었네요.. 변경 처리하겠습니다 :)
해당 관련 속성은 global.css 에 정의되어 있습니다

2018-09-13 02:04 UTC, JunuSinclair commented on components/src/pagination/index.tsx
> +                active: currentPage === pageNumber,
기존 active 클래스로 처리를 하던 부분인데 제거하는걸 잊었네요... 제거 하겠습니다~

2018-09-13 02:08 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
2번에 대해서는 현재 저도 딱히 떠오르는 바는 없는데 추후 어떤식으로 사용될지 몰라 일단 남겨둔 상태입니다.
혹시 우려되는 바가 있으신가요??

2018-09-13 02:11 UTC, kyungmi commented on components/src/pagination/index.tsx
> +                museo_sans: true,
제가 정확히 구조를 몰라서 그러는데, `global.css`는 컴포넌트별 css 파일에는 임포트되지 않나요?

2018-09-13 02:15 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
오버스펙이라면 제거하는게 좋을 것 같습니다.
꼭 필요하다면 여러 item들을 자식으로 가지는 모든 컴포넌트(select box 라던지)에 통일된 스펙으로 포함되는게 좋을 것 같습니다. props를 내려주는 방식은 좀 더 생각해볼 여지가 있을 것 같아요.

2018-09-13 02:21 UTC, incleaf commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
현재 이런식으로 사용되고 있습니다. 컴포넌트 선언 시점에서는 페이지 정보를 알 수 없어서 함수를 콜백으로 받아서 처리하고 있습니다.
```tsx
<Pagination
  currentPage={page}
  item={{
     el: Link,
     getProps: (p) => ({ to: `/my-select-history?page=${p}` } as LinkProps),
  }}
  isMobile={true}
  totalPages={Math.ceil(mySelectHistory.itemCount / 10)}
/>
```

2018-09-13 02:23 UTC, incleaf commented on components/src/pagination/index.tsx
> +                museo_sans: true,
@JunuSinclair stylesheets 폴더 아래에 있는 스타일시트들은 별개로 보셔야합니다~ `variables.css`에 추가하는 등의 식으로 변경해야 할 것 같아요.

2018-09-13 02:25 UTC, incleaf approved these changes

2018-09-13 02:25 UTC, incleaf commented on components/src/pagination/index.css
> +.THRPaging {
컴포넌트명과 맞춰서 `Paging`을 `Pagination`으로 바꾸는 건 어떨까요?

2018-09-13 02:25 UTC, incleaf commented on components/src/pagination/index.tsx
> +    component?: React.ReactType<PaginationProps>;
`React.ComponentType`으로 수정해주세요~ https://github.com/ridi/rsg/pull/24

2018-09-13 02:25 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
제 생각에는 이 경우는 `<Link>`로 대체하는 것 보다는 `onPageMove` 같은 이벤트 처리로 바뀌는게 좋지 않을까 싶어요. `<Pagination>` 컴포넌트가 제공해줄 기능으로도 적합해 보이고요. 추상화 관점에서도 컴포넌트에 포함되는 하위 멤버까지 상위에서 직접 관리하는건 좋지 않을 것 같아요.

```
<Pagination
    currentPage={page}
    onPageMove={(p) => { window.location.href= `/my-select-history?page=${p}`; } }
    isMobile
    totalPages={...} 
/>
```

2018-09-13 02:26 UTC, incleaf requested changes
Request Changes

2018-09-13 02:29 UTC, JunuSinclair commented on components/src/pagination/index.css
> +.THRPaging {
좋습니다. 훨씬 나아질 것 같네요

2018-09-13 02:32 UTC, incleaf commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
앵커 태그 형태가 아니면 웹 접근성에 악영향을 미치는 다음과 같은 단점들이 있어서 부적합하다고 생각합니다.
1. 자바스크립트가 Disable 되어있을 경우 동작하지 않음
2. 서치엔진 파싱 불가능
3. 브라우저 기능 (CMD + Click, Link Preview 등) 지원 불가

2018-09-13 02:47 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
Link(혹은 Anchor tag)를 사용해서 처리할 수 있는 부분은 사용하는 것이 시멘틱하다는 생각이 되는데요, 반대로 이벤트처리로 변경했을때 얻을 수 있는 이점은 무엇이 있을까요??

2018-09-13 02:52 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
```js
<Pagination
    currentPage={page}
    totalPage={total}
    isMobile={true}
    onChange={page => {...}}
>
    <Pagination.items component={Link} href={p => `/my-select-history?page=${p}`} />
</Pagination>
```
`item` 프로퍼티를 빼내서 위와 같은 형태는 어떠신가요?
`<Link>`를 사용하지 않을 수도 있으니 `onChange` 이벤트도 처리할 수 있게끔 추가하고요.

2018-09-13 02:57 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@JunuSinclair 별다른 이점은 없습니다. 개인적으로 `<Pagination>`의 하위 컴포넌트를 직접 제어한다는게 어색하게 느껴져서요. 다른 컴포넌트에도 동일한 스펙으로 적용된다면 그대로 가도 상관 없을 것 같습니다.

2018-09-13 03:08 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
사용하는 입장에서 컴포넌트가 분산되어 오히려 번거로워지지 않을까 하는 우려가 드는데 다른분들 의견이 궁금합니다...
일단 위와 같이 변경된다면 onChange 는 items 쪽에 가는게 더 맞지 않을까요??

2018-09-13 03:10 UTC, krazijames commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
위에서는 마치 `<Pagination.items />`가 아닌 다른 children을 넣을 수 있을 것 처럼 보여서 조금 혼동이 있을 수도 있을 것 같은데요, 아래와 같은 형태는 어떤가요?

```jsx
const LinkPageButton = ({page, ...extraProps}) => (
  <Button
    {...extraProps}
    component={Link}
    to={`/my-select-history?page=${page}`}
  >
    {page}
  </Button>
);
<Pagination pageButtonRenderer={LinkPageButton} />

const AnchorPageButton = ({page, ...extraProps}) => (
  <Button
    {...extraProps}
    component="a"
    href={`/my-select-history?page=${page}`}
  >
    {page}
  </Button>
);
<Pagination pageButtonRenderer={AnchorPageButton} />
```

2018-09-13 03:16 UTC, krazijames commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
아무래도 *사용하는 입장에서 컴포넌트가 분산되어 오히려 번거로워지지 않을까 하는 우려*가 되네요. first, prev, next 버튼 까지 있으니 조금 더 생각해봐야겠습니다. 😓

2018-09-13 03:23 UTC, Junu-Sinclair commented on components/src/pagination/index.tsx
> +                museo_sans: true,
그렇군요 수정해둘게요~

2018-09-13 03:23 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
넵 ㅎㅎ 사실 전체 컴포넌트간 일관성만 지켜진다면 어떻게 사용하든 상관 없을 것 같습니다. 사용하는 쪽에서 불편함이 적은 방향으로 작업해주세요. 리팩토링은 일단 기본 컴포넌트가 다 작업된 후에 여유가 생길때 더 고민해보고 시작해도 좋을 것 같습니다.
현재로써는 자유도가 더 높은게, 사용 케이스들을 취합하는데 더 적합할거라는 생각도 드네요.

2018-09-13 03:30 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@krazijames 어차피 prev, next, first, last 버튼도 동작방식에 있어서는 동일하니까, 제안해주신 방법으로 해도 좋을 것 같아요. 현재 방식보다는 훨씬 이해하기에도 좋을 것 같습니다.

2018-09-13 03:36 UTC, krazijames commented on components/src/pagination/index.tsx
>        <h2 className="a11y indent_hidden">페이지 내비게이션</h2>
이것은 제거해도 되지 않을까요?

2018-09-13 03:38 UTC, krazijames commented on components/src/pagination/index.css
> +  & .DotIcon {
위의 `ArrowIcon`과 더불어 적절한 prefix가 붙었으면 좋겠습니다.

2018-09-13 03:49 UTC, incleaf commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
A
```tsx
const AnchorPageButton = ({page, ...extraProps}) => (
  <Button
    {...extraProps}
    component="a"
    href={`/my-select-history?page=${page}`}
  >
    {page}
  </Button>
);
<Pagination pageButtonRenderer={AnchorPageButton} />
```

B
```tsx
<Pagination 
  component="a" 
  getComponentProps={p => ({ href: `/my-select-history?page=${p}` })}
/>
```

A가 제안주신 방법이고 B가 현재 방법인데요, 현재 방법이 더 간략한 방법 아닐까요? 🤔

2018-09-13 03:54 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@incleaf 
현재 방법은 더 명확하게 쓰면 
```
<Pagination 
  item={{
    component="a" 
    getComponentProps={p => ({ href: `/my-select-history?page=${p}` })}
}}
/>
```
입니다.
`item` 프로퍼티를 `pageButtonRenderer`로 바꾸고, component 자체를 그 값으로 받을 수 있게 변경되기 때문에 사용하려면 좀 더 많은 작업이 들어가긴 하겠지만 이해하기에는 더 명확하다고 생각합니다.

2018-09-13 04:46 UTC, krazijames commented on components/src/pagination/index.tsx
>    isMobile: boolean;
`isMobile: boolean` 보다는 `visiblePages: number`와 `showGoFirstButton: boolean`으로 받는 것은 어떨까요? `isMobile`은 값에 따른 동작을 예상하기가 어려울 것 같고, `sibilingPagesRange`가 하드코딩 돼있어서 개선되면 좋을 것 같습니다.

2018-09-13 04:57 UTC, kyungmi approved these changes

2018-09-13 05:53 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>    isMobile: boolean;
모바일과 PC 로 나누는게 아니라 특정 갯수를 상수화 해서 지정해놓고 그것을 이용하는 방식을 예상하시는 거죠...?? Range 에 5, 10 이렇게 인지 가능하게 지정이 되어있구요.

2018-09-13 05:54 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>        <h2 className="a11y indent_hidden">페이지 내비게이션</h2>
a11y 는 voice over 등의 접근성을 목적으로 들어있는거라서요 왠만하면 유지하는게 좋지 않을까 싶습니다.
이것에 대한 문의도 종종 들어오고 있구요. 
아니면 저렇게 감싸고있는 부분이 아니라 개별적이 버튼에서 인지가 가능하다면 여기선 필요가 없을 것 같긴 하네요.

2018-09-13 05:57 UTC, krazijames commented on components/src/pagination/index.tsx
>    isMobile: boolean;
*특정 갯수를 상수화*한다기 보다는 기본값만 있고 사용하는 쪽에서 아무 개수나 넣을 수 있도록 하는 걸 의미했습니다.

2018-09-13 05:57 UTC, JunuSinclair commented on components/src/pagination/index.css
> +  & .DotIcon {
Svg_DotIcon

같이 앞에 Svg를 붙이는 것 정도가 생각이 나는데 혹시 고려해보신 네이밍이 있으신가요?

2018-09-13 06:00 UTC, krazijames commented on components/src/pagination/index.tsx
>        <h2 className="a11y indent_hidden">페이지 내비게이션</h2>
아 그런 기능이 있었군요. Styleguidist에서는 화면에 그대로 보여지다보니... 그런 용도라면 `a11y`, `indent_hidden`과 관련된 CSS도 `components` 패키지로 복사해서 사용하는 것이 좋겠습니다. :)

2018-09-13 08:50 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
경미님이 마지막으로 정리해주신 형태로 'pageButtonRenderer' 를 이용하는 식 정도까지만 정리하겠습니다~ 리펙토링은 말씀해주신대로 여유될때 차차 정리하는 식으로 하구요!

2018-09-13 09:01 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@JunuSinclair 제안해 주신 방식이 ["render props" 패턴](https://reactjs.org/docs/render-props.html)과 거의 흡사한데, 이름을 맞추는 것도 좋을 것 같아요. `render` prefix를 붙여서 `renderItem` 이라던지...

2018-09-13 09:22 UTC, krazijames commented on components/src/pagination/index.css
> +  & .DotIcon {
`THRPagination_GoNextIcon`은 어떨까 싶습니다 ㅎㅎ 클래스명에  svg, dot 보다는 역할 위주로 기술되면 좋을 것 같아요.

2018-09-13 09:27 UTC, incleaf commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@kyungmi 아 `item`을 빼먹었네요 ㅎㅎ 만약 현행을 유지한다면 `item`이 제거되고 Flat한 형태로 가는 게 더 좋다고 생각합니다.

@JunuSinclair 경미님이 마지막으로 정리해주신 형태는 `pageButtonRenderer`를 이용하는 방법이 아니라 현재 구조를 다시 잡아주신 형태인데, 어떤 방법으로 진행한다는 이야기신가요?

2018-09-13 09:39 UTC, JunuSinclair commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@incleaf 
 아 renderer 을 외부에서 넘겨주는 식 이었나요 혹시,
 내부에서 메서드로 분리해서하는걸 생각했습니다.
 일단 내부에서 renderer 메서드로 분리해서 사용하고 `item`을 제외한 플랫한 형태로 변경하는 것 까지 정리 하면 어떨까요?
 pagination 이 merge 되고 나면 button group 작업하면서 외부에서 button renderer 를 props 로 넘기는 걸로 정리하는걸 생각하고 있습니다.

2018-09-13 09:43 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
스레드가 길어지면서 의견이 섞인것 같네요 ㅋㅋ
결과적으로 이런 형태로 사용하는 것으로 합의되었다고 생각했어요.
```js
<Pagination renderItem={(page, ...) => <Link to={`/path/to/{page}`} />} />
```

2018-09-13 10:00 UTC, incleaf commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
```tsx
<Pagination renderItem={(page, ...) => <Link to={`/path/to/{page}`} />} />
```
위 코드는 버튼에 대한 스타일링이 안 되어있는 상태 아닌가요? Rest Parameters를 넘겨도 마찬가지 일 것 같구요. ㅎㅎ
기존 코드베이스의 `component`는 단순히 `Button`의 Wrapper를 넘기고 Props 전달은 컴포넌트 내부에 위임하는 형태였는데 rendre props 형태는 Props 전달을 사용처에 위임하는 형태여서 조금 다른 형태가 될 것 같네요.

2018-09-13 10:02 UTC, kyungmi commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
@incleaf `Pagination` 컴포넌트 내부에서 `React.cloneElement();`를 사용해서 renderItem 함수 실행 결과를 확장할 수 있지 않을까요?

2018-09-13 10:08 UTC, incleaf commented on components/src/pagination/index.tsx
>        getProps = (page?: number) => ({}),
넵, 가능할 것 같습니다. 다만 로직들이 겉으로 드러나지 않다보니 렌더 결과를 예측하기 힘들 수 있을 것 같아요.

2018-09-13 10:10 UTC, incleaf requested changes

2018-09-13 10:10 UTC, incleaf commented on components/components.css
> +}
`components.css`가 아니라 `common.css` 혹은 `global.css`같은 다른 파일을 만들어서 적용하는 것이 낫지 않을까요?

2018-09-13 10:12 UTC, incleaf requested changes

2018-09-13 10:12 UTC, incleaf commented on components/src/pagination/index.tsx
> +  component?: React.ComponentType<PaginationProps>;
`React.ComponentType`으로 수정되어야 합니다.

2018-09-13 10:12 UTC, incleaf commented on components/src/pagination/index.tsx
> +      key={`pagination_${page}_page`}
key 값으로 `page`만 넘겨도 되지 않을까요?

2018-09-14 03:48 UTC, antiline commented on components/src/pagination/index.tsx
> +      key={`pagination_${page}_page`}
`_page` 이걸 생략하자는 말씀이신거죠? 저는 `_page` 명시하는게 맞다고 봅니다.

2018-09-14 04:10 UTC, incleaf commented on components/src/pagination/index.tsx
> +      key={`pagination_${page}_page`}
Key는 유니크함을 유지하기만 하면 되어서 불필요하다고 느껴지는데 스트링 리터럴을 붙이면 어떤 이점이 있나요?

2018-09-14 04:41 UTC, krazijames commented on components/src/pagination/index.tsx
> +      key={`pagination_${page}_page`}
다른 얘기긴 한데 `key`는 루프를 도는 쪽에서 주입시키는 게 좋을 것 같습니다.

2018-09-14 06:12 UTC, antiline commented on components/src/pagination/index.tsx
> +      key={`pagination_${page}_page`}
page만 넘긴다는게 아래와 같이 쓰자는거죠? 그러면 괜찮습니다.
```
key=key={page.toString()}
```

저는 첫 코맨트 작성할때
```
key={`pagination_${page}`}
```
라고 이해했습니다.

2018-09-14 06:17 UTC, JunuSinclair commented on components/src/pagination/index.tsx
> +  component?: React.ComponentType<PaginationProps>;
저 뒤에 제네릭으로 처리되는건 Wrapper component 로 쓰는경우에만 처리하고 그 외에는 불필요한거죠??

2018-09-17 02:20 UTC, antiline approved these changes

2018-09-17 07:54 UTC, JunuSinclair commented
@incleaf @krazijames 버튼 그룹까지 반영해두었습니다.

2018-09-18 06:22 UTC, closed without merging