Add Button Group
ridi/rsg pull request #25
Opened 2018-09-14 01:56 UTC by JunuSinclair

Add Button Group Wrapper Component
- using THRButton

2018-09-14 03:14 UTC, kyungmi commented on components/src/button_group/index.tsx
> +  collapse?: boolean;
UI 라이브러리에서 보통 `collapse`는 다른 의미(=콘텐츠 숨김)로 사용되는 것 같은데요. 혼동될 수 있을 것 같아요. 이름을 바꾸는게 좋을 것 같습니다.
그리고 `<ButtonGroup>`에서 `collapse`를 꼭 옵션으로 두어야 할까요? `Group`이라는 이름에 이미 UI측면에서 하위 컴포넌트들을 묶겠다는 의도가 들어 있는 것 같아서요.

2018-09-14 03:31 UTC, krazijames commented on components/src/button_group/index.css
> +    flex: 0 1 auto;
`flex`보다는 `display: inline-block`을 사용하는 것이 나을 것 같습니다. `.THRButtonGroup-vertical`과 일관성을 유지하는 측면도 있고, 겉을 감싸는 컨테이너 컴포넌트의 `display` 속성은 사용하는 쪽에서 바꾸고 싶을 수도 있을 것 같아요.

2018-09-14 03:31 UTC, krazijames commented on components/src/button_group/index.tsx
> +  } = props;
다른 컴포넌트와 마찬가지로 `component` prop이 추가되면 좋겠습니다.

2018-09-14 03:31 UTC, krazijames commented on components/src/button_group/index.tsx
> +      className={classNames([
굳이 배열로 감싸지 않아도 될 것 같습니다.

2018-09-14 03:37 UTC, krazijames commented on components/src/button_group/README.md
> +    <Button outline={true}>리디북스</Button>
`={true}`는 생략해도 좋을 것 같아요

2018-09-14 03:41 UTC, krazijames commented on components/src/button_group/README.md
> +```
문서 스타일은 어차피 나중에 전체적으로 수정할 것 같지만 markdown을 사용하는 이점을 살려보는 건 어떨까요 ㅎㅎ
````markdown
### Horizontal
```js
<ButtonGroup>
  <Button color="blue">리디북스</Button>
  <Button outline>리디북스</Button>
</ButtonGroup>
```
#### Collapsed
```js
<ButtonGroup collapse>
  <Button color="blue">리디북스</Button>
  <Button outline>리디북스</Button>
  <Button outline>리디북스</Button>
  <Button outline>리디북스</Button>
  <Button outline>리디북스</Button>
</ButtonGroup>
```

### Vertial
```js
<ButtonGroup orientation="vertical">
  <Button>리디북스</Button>
  <Button>리디북스</Button>
</ButtonGroup>
```
#### Collapsed
```js
<ButtonGroup orientation="vertical" collapse>
  <Button>리디북스</Button>
  <Button>리디북스</Button>
  <Button>리디북스</Button>
  <Button>리디북스</Button>
  <Button>리디북스</Button>
  <Button>리디북스</Button>
</ButtonGroup>
```
````

2018-09-14 03:45 UTC, JunuSinclair commented on components/src/button_group/README.md
> +```
좋습니다! 여기서 정리해두고 추후에 수정할때 같이 한번씩 다듬으면 좋겠네요 :)

2018-09-14 03:47 UTC, JunuSinclair commented on components/src/button_group/index.tsx
> +  collapse?: boolean;
아 그러면 버튼들이 붙는 형태만 group 으로 쓰고 그냥 나열된건 개별적으로 쓰는걸 생각하시는거죠?

2018-09-14 03:48 UTC, kyungmi commented on components/src/button_group/index.tsx
> +  collapse?: boolean;
@JunuSinclair 네 맞아요.

2018-09-14 06:14 UTC, JunuSinclair commented on components/src/button_group/index.tsx
> +  collapse?: boolean;
@kyungmi 반영했습니다~

2018-09-14 06:15 UTC, JunuSinclair commented on components/src/button_group/index.css
> +    flex: 0 1 auto;
네네 전에 그랬던 적이 있던 것 같아서, 수정하면 좋은 부분인 것 같네요! 수정했습니다.

2018-09-14 06:17 UTC, kyungmi approved these changes

2018-09-14 06:33 UTC, krazijames commented on components/src/button_group/index.tsx
> +      ${className}`
`classNames()` 를 안쓰면 `undefined`가 그대로 출력됩니다.
코멘트 했던것은 `classNames(['a', 'b'])`를 `classNames('a', 'b')`처럼 배열 없이 써도 된다는 것이었어요 ㅎㅎ

2018-09-14 06:37 UTC, incleaf requested changes

2018-09-14 06:37 UTC, incleaf commented on components/components.css
> +@import "src/button_group/index.css";
테헤란으로 변경하면서 바꾸려고 했던 부분인데 `button_group`을 `ButtonGroup`으로 바꾸는 게 좋을 것 같아요~

2018-09-14 06:37 UTC, incleaf commented on components/src/button_group/index.tsx
> +  component?: React.ComponentType<ButtonGroupProps>;
`React.ComponentType`으로 변경되어야 합니다

2018-09-14 06:37 UTC, incleaf commented on components/src/button_group/index.tsx
> +  children: React.ReactChildren;
`React.SFC`에 기본적으로 `children`은 포함되어 있는데요, 혹시 `required`한 값이라는 걸 나타내기 위해 추가하신건가요?

2018-09-14 06:37 UTC, incleaf commented on components/src/button_group/index.tsx
> +      ${className}`
1. `className`이 `undefined`일 수 있습니다.
2. 질문: 이렇게 클래스네임을 작성하면 `\n` 캐릭터가 포함되지는 않나요?

2018-09-14 07:27 UTC, JunuSinclair commented on components/components.css
> +@import "src/button_group/index.css";
저도 이거 바꿀까하다가 말았는데 변경처리할게요~

2018-09-14 07:27 UTC, JunuSinclair commented on components/src/button_group/index.tsx
> +  children: React.ReactChildren;
아 이건 제가 그 부분을 몰랐습니다;; 제거할게요~

2018-09-14 08:53 UTC, incleaf commented on components/components.css
> +@import "src/button_group/index.css";
아 저는 camelCase 말고 PascalCase를 의미한거였는데... 컴포넌트는 보통 PascalCase를 사용하니 PascalCase가 낫지 않을까요?

2018-09-17 00:46 UTC, JunuSinclair commented on components/components.css
> +@import "src/button_group/index.css";
다른 컴포넌트 디렉토리도 마찬가지로 함께 변경될 것을 생각하고 계신거죠?

2018-09-17 03:14 UTC, JunuSinclair commented
@incleaf 반영사항 확인해주시면 머지 후에 pagination에 button group 반영하겠습니다.

2018-09-17 06:41 UTC, incleaf approved these changes

2018-09-17 06:58 UTC, JunuSinclair commented
@krazijames 머지 하겠습니다~

2018-09-17 07:02 UTC, merged