Add Tabs Component
ridi/rsg pull request #37
Opened 2018-10-01 02:19 UTC by krazijames

## Changes
- Create `Tabs`, `Tab` components
- Copy CSS from `stylesheets`
- Add `activeColor`, `flex` props
- Add `value`, `onClick` props
- Rename CSS classes

2018-10-02 08:20 UTC, JunuSinclair commented on components/src/Tabs/index.tsx
> +  title?: string;
title 보다는 buttonText / buttonSubText 등이 더 낫지 않을까요..?? 뭔가 버튼의 title 이 있고 탭 컴포넌트 내에 여러개의 title이 있는게 어색하게 느껴지는데.. 음.. 저만 그런걸 수도 있으니 다른분들 의견 들어보고 싶습니다.

2018-10-02 08:39 UTC, krazijames commented on components/src/Tabs/index.tsx
> +  title?: string;
현재 `rui_components.html`에 스타일이 다른 두 텍스트가 들어가도록 돼있어서 `subtitle` 개념을 컴포넌트에 넣게됐는데요. 애초에 생각했던 것은 `title`과 `subtitle`을 prop으로 넘기지 않고, 탭 속의 내용은
```jsx
<Tab>일반도서 <span className="xxx">30</span></Tab>
```
처럼 사용하는 측에 맡기고 싶었습니다.
`prop`으로 남겨둘 것이라면 이름에서 `button`을 뺀 `text`/`subtext`가 좀 더 간결할 것 같습니다.

2018-10-02 08:44 UTC, JunuSinclair commented on components/src/Tabs/index.tsx
> +  title?: string;
tag 처럼 사용할 수 있는 저 방식이 저도 더 좋은 것 같습니다.

2018-10-04 01:07 UTC, incleaf requested changes

2018-10-04 01:07 UTC, incleaf commented on components/src/Tabs/index.tsx
> +  active?: boolean;
`active` 상태를 `Tab` 컴포넌트에서 직접 지정하는 방식보다는 `Tabs`에 `activeValue`와 같은 Prop을 추가해서 내부적으로 처리하는 게 더 간결하지 않을까요?

현재

```jsx
<Tabs>
  <Tab value="general" active={activeValue === "general"}>일반</Tab>
  <Tab value="romance" active={activeValue === "romance"}>로맨스</Tab>
  <Tab value="fantasy" active={activeValue === "fantasy"}>판타지</Tab>
</Tabs>
```

제안

```jsx
<Tabs activeValue="general">
  <Tab value="general">일반</Tab>
  <Tab value="romance">로맨스</Tab>
  <Tab value="fantasy">판타지</Tab>
</Tabs>
```

2018-10-04 06:44 UTC, krazijames commented on components/src/Tabs/index.tsx
> +  active?: boolean;
네. 제안해주신 방법이 더 깔끔하지만 `value` 없이 `href`만 사용할 때 `active`처리를 어떻게 해야할 지 딱히 방법이 떠오르지 않아서 `Radio` 컴포넌트와 동일하게 동작하도록 두었습니다.

`active`여부는 무조건 `value`를 통해 한다든지, `activeHref`를 추가로 둘 수도 있겠지만 썩 좋은 방법은 아닌 것 같아서요.. 혹시 아이디어가 있으신지요?

2018-10-04 06:56 UTC, incleaf commented on components/src/Tabs/index.tsx
> +  active?: boolean;
아, 그런 상황도 있었군요 ㅎㅎ; 그렇다면 이런 방법도 있을 것 같습니다. `active`는 optional한 Prop으로 정의하구요.

```jsx
<Tabs active={{ key: 'href', value: '/general' }}>
  <Tab href="/general">일반</Tab>
  <Tab href="/romance">로맨스</Tab>
  <Tab href="/fantasy">판타지</Tab>
</Tabs>
```

지금 구조도 괜찮은 구조인 것 같아서 진욱님이 원하는 방향으로 선택하시면 될 것 같아요~

2018-10-04 06:56 UTC, incleaf approved these changes

2018-10-07 08:57 UTC, Junu-Sinclair approved these changes

2018-10-08 05:09 UTC, krazijames commented on components/src/Tabs/index.tsx
> +  active?: boolean;
이부분은 더 고민이 필요할 것 같아요. 현재는 렌더링이 되는 것까지 목표로 하기로 했으니, 일단은 지금 상태로 머지하겠습니다!

2018-10-08 05:10 UTC, merged